on:
  push:
    branches:
      - main
      - staging/*
  pull_request:

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: analogdevicesinc/doctools
        path: doctools
    - name: Install pip packages
      working-directory: docs
      run: |
        pip install pip --upgrade
        pip install -r requirements.txt --upgrade

    - name: Install bundler dependencies
      run: >-
        npm install
        rollup
        @rollup/plugin-terser
        @rollup/plugin-alias
        sass

    - name: Bundle web scripts
      run: >-
        node_modules/.bin/rollup -c
        ci/rollup.config.landing-page.mjs

    - name: Bundle web styles
      run: >-
        node_modules/.bin/sass
        --load-path ./doctools/adi_doctools/theme/cosmic/style
        style/landing-page.bundle.scss:docs/sources/landing-page.min.css
        --style compressed

    - name: Build doc
      working-directory: docs
      run: |
        make html SPHINXOPTS="-W --keep-going"

    - name: Store the generated doc
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: docs/_build/html

  deploy:
    runs-on: ubuntu-latest
    needs: [build-doc]
    permissions:
      contents: write
    if: >
      github.ref == 'refs/heads/main' ||
      github.event_name == 'pull_request'

    steps:
    - uses: analogdevicesinc/doctools/gh-pages-deploy@action
      with:
        new_tag: 'false'
        tag: ${{ github.ref_name }}
        name: html

